//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/Inputs/GameInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputs"",
    ""maps"": [
        {
            ""name"": ""Inputs"",
            ""id"": ""2e7e56d3-f716-4439-bf06-23ddf3004e86"",
            ""actions"": [
                {
                    ""name"": ""Alien1Hunger"",
                    ""type"": ""Button"",
                    ""id"": ""477df849-4846-4369-89be-3c696ee8f7b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien1Fun"",
                    ""type"": ""Button"",
                    ""id"": ""601b3de5-722c-4806-825c-b0ee6acbab1c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien1Taser"",
                    ""type"": ""Button"",
                    ""id"": ""fc71aa42-7ffb-4ef8-a99d-a9dedb9feb09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien2Fun"",
                    ""type"": ""Button"",
                    ""id"": ""14799203-ba85-49bc-a5aa-1b9817119ac3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien2Taser"",
                    ""type"": ""Button"",
                    ""id"": ""24cdeab6-1716-4935-8e9a-1cda1ad2cf76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien2Health"",
                    ""type"": ""Button"",
                    ""id"": ""32e86da5-b7f6-4be4-9d88-fd53ae16534c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien3Health"",
                    ""type"": ""Button"",
                    ""id"": ""c7ce244b-3042-451a-896d-d9262c590c84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien3Fun"",
                    ""type"": ""Button"",
                    ""id"": ""5de0e570-4937-438d-985f-6ba9e54aa7b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien3Hunger"",
                    ""type"": ""Button"",
                    ""id"": ""59a4627e-1e41-472a-890d-0edc26776ec8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien4Health"",
                    ""type"": ""Button"",
                    ""id"": ""4e5c3f74-751c-467b-a28c-70de1e1c43a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien4Taser"",
                    ""type"": ""Button"",
                    ""id"": ""ab08c873-3dbf-471c-9cbe-dbac58402ca8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alien4Hunger"",
                    ""type"": ""Button"",
                    ""id"": ""0b843e14-d8a0-490e-a9b1-7bee7881d980"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""208eb7e3-1766-4be6-8e4b-2e8c4be3b7a7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien1Hunger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb44e568-67d9-4b3a-baba-a2e0d6f3a32c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien1Fun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14c43d77-ebc3-4edd-a32b-b6cac2c78f8d"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien1Taser"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""734e6472-7c6c-4132-92d3-df14ff0e8f5b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien2Fun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""158ea95a-e2c8-4d5b-8528-867d73a26493"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien2Taser"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c44f1356-6c86-487e-9b6f-9281763a4b16"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien2Health"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0b9116e-c022-4ec5-b22b-f1ccdc00449d"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien3Hunger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb9f8416-5ade-476a-a6d3-785ca6457ced"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien3Fun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f5a14ff-b45c-4ce2-afb2-909cb6e4b4e2"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien3Health"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1bc84fa-02cc-44a6-adb3-678a39d4048e"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien4Health"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6cf2052-6651-4336-b3c5-5926b92ce966"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien4Taser"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84aa9690-3102-4f04-b53e-e252313b523b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alien4Hunger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Inputs
        m_Inputs = asset.FindActionMap("Inputs", throwIfNotFound: true);
        m_Inputs_Alien1Hunger = m_Inputs.FindAction("Alien1Hunger", throwIfNotFound: true);
        m_Inputs_Alien1Fun = m_Inputs.FindAction("Alien1Fun", throwIfNotFound: true);
        m_Inputs_Alien1Taser = m_Inputs.FindAction("Alien1Taser", throwIfNotFound: true);
        m_Inputs_Alien2Fun = m_Inputs.FindAction("Alien2Fun", throwIfNotFound: true);
        m_Inputs_Alien2Taser = m_Inputs.FindAction("Alien2Taser", throwIfNotFound: true);
        m_Inputs_Alien2Health = m_Inputs.FindAction("Alien2Health", throwIfNotFound: true);
        m_Inputs_Alien3Health = m_Inputs.FindAction("Alien3Health", throwIfNotFound: true);
        m_Inputs_Alien3Fun = m_Inputs.FindAction("Alien3Fun", throwIfNotFound: true);
        m_Inputs_Alien3Hunger = m_Inputs.FindAction("Alien3Hunger", throwIfNotFound: true);
        m_Inputs_Alien4Health = m_Inputs.FindAction("Alien4Health", throwIfNotFound: true);
        m_Inputs_Alien4Taser = m_Inputs.FindAction("Alien4Taser", throwIfNotFound: true);
        m_Inputs_Alien4Hunger = m_Inputs.FindAction("Alien4Hunger", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Inputs
    private readonly InputActionMap m_Inputs;
    private List<IInputsActions> m_InputsActionsCallbackInterfaces = new List<IInputsActions>();
    private readonly InputAction m_Inputs_Alien1Hunger;
    private readonly InputAction m_Inputs_Alien1Fun;
    private readonly InputAction m_Inputs_Alien1Taser;
    private readonly InputAction m_Inputs_Alien2Fun;
    private readonly InputAction m_Inputs_Alien2Taser;
    private readonly InputAction m_Inputs_Alien2Health;
    private readonly InputAction m_Inputs_Alien3Health;
    private readonly InputAction m_Inputs_Alien3Fun;
    private readonly InputAction m_Inputs_Alien3Hunger;
    private readonly InputAction m_Inputs_Alien4Health;
    private readonly InputAction m_Inputs_Alien4Taser;
    private readonly InputAction m_Inputs_Alien4Hunger;
    public struct InputsActions
    {
        private @GameInputs m_Wrapper;
        public InputsActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Alien1Hunger => m_Wrapper.m_Inputs_Alien1Hunger;
        public InputAction @Alien1Fun => m_Wrapper.m_Inputs_Alien1Fun;
        public InputAction @Alien1Taser => m_Wrapper.m_Inputs_Alien1Taser;
        public InputAction @Alien2Fun => m_Wrapper.m_Inputs_Alien2Fun;
        public InputAction @Alien2Taser => m_Wrapper.m_Inputs_Alien2Taser;
        public InputAction @Alien2Health => m_Wrapper.m_Inputs_Alien2Health;
        public InputAction @Alien3Health => m_Wrapper.m_Inputs_Alien3Health;
        public InputAction @Alien3Fun => m_Wrapper.m_Inputs_Alien3Fun;
        public InputAction @Alien3Hunger => m_Wrapper.m_Inputs_Alien3Hunger;
        public InputAction @Alien4Health => m_Wrapper.m_Inputs_Alien4Health;
        public InputAction @Alien4Taser => m_Wrapper.m_Inputs_Alien4Taser;
        public InputAction @Alien4Hunger => m_Wrapper.m_Inputs_Alien4Hunger;
        public InputActionMap Get() { return m_Wrapper.m_Inputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputsActions set) { return set.Get(); }
        public void AddCallbacks(IInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_InputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InputsActionsCallbackInterfaces.Add(instance);
            @Alien1Hunger.started += instance.OnAlien1Hunger;
            @Alien1Hunger.performed += instance.OnAlien1Hunger;
            @Alien1Hunger.canceled += instance.OnAlien1Hunger;
            @Alien1Fun.started += instance.OnAlien1Fun;
            @Alien1Fun.performed += instance.OnAlien1Fun;
            @Alien1Fun.canceled += instance.OnAlien1Fun;
            @Alien1Taser.started += instance.OnAlien1Taser;
            @Alien1Taser.performed += instance.OnAlien1Taser;
            @Alien1Taser.canceled += instance.OnAlien1Taser;
            @Alien2Fun.started += instance.OnAlien2Fun;
            @Alien2Fun.performed += instance.OnAlien2Fun;
            @Alien2Fun.canceled += instance.OnAlien2Fun;
            @Alien2Taser.started += instance.OnAlien2Taser;
            @Alien2Taser.performed += instance.OnAlien2Taser;
            @Alien2Taser.canceled += instance.OnAlien2Taser;
            @Alien2Health.started += instance.OnAlien2Health;
            @Alien2Health.performed += instance.OnAlien2Health;
            @Alien2Health.canceled += instance.OnAlien2Health;
            @Alien3Health.started += instance.OnAlien3Health;
            @Alien3Health.performed += instance.OnAlien3Health;
            @Alien3Health.canceled += instance.OnAlien3Health;
            @Alien3Fun.started += instance.OnAlien3Fun;
            @Alien3Fun.performed += instance.OnAlien3Fun;
            @Alien3Fun.canceled += instance.OnAlien3Fun;
            @Alien3Hunger.started += instance.OnAlien3Hunger;
            @Alien3Hunger.performed += instance.OnAlien3Hunger;
            @Alien3Hunger.canceled += instance.OnAlien3Hunger;
            @Alien4Health.started += instance.OnAlien4Health;
            @Alien4Health.performed += instance.OnAlien4Health;
            @Alien4Health.canceled += instance.OnAlien4Health;
            @Alien4Taser.started += instance.OnAlien4Taser;
            @Alien4Taser.performed += instance.OnAlien4Taser;
            @Alien4Taser.canceled += instance.OnAlien4Taser;
            @Alien4Hunger.started += instance.OnAlien4Hunger;
            @Alien4Hunger.performed += instance.OnAlien4Hunger;
            @Alien4Hunger.canceled += instance.OnAlien4Hunger;
        }

        private void UnregisterCallbacks(IInputsActions instance)
        {
            @Alien1Hunger.started -= instance.OnAlien1Hunger;
            @Alien1Hunger.performed -= instance.OnAlien1Hunger;
            @Alien1Hunger.canceled -= instance.OnAlien1Hunger;
            @Alien1Fun.started -= instance.OnAlien1Fun;
            @Alien1Fun.performed -= instance.OnAlien1Fun;
            @Alien1Fun.canceled -= instance.OnAlien1Fun;
            @Alien1Taser.started -= instance.OnAlien1Taser;
            @Alien1Taser.performed -= instance.OnAlien1Taser;
            @Alien1Taser.canceled -= instance.OnAlien1Taser;
            @Alien2Fun.started -= instance.OnAlien2Fun;
            @Alien2Fun.performed -= instance.OnAlien2Fun;
            @Alien2Fun.canceled -= instance.OnAlien2Fun;
            @Alien2Taser.started -= instance.OnAlien2Taser;
            @Alien2Taser.performed -= instance.OnAlien2Taser;
            @Alien2Taser.canceled -= instance.OnAlien2Taser;
            @Alien2Health.started -= instance.OnAlien2Health;
            @Alien2Health.performed -= instance.OnAlien2Health;
            @Alien2Health.canceled -= instance.OnAlien2Health;
            @Alien3Health.started -= instance.OnAlien3Health;
            @Alien3Health.performed -= instance.OnAlien3Health;
            @Alien3Health.canceled -= instance.OnAlien3Health;
            @Alien3Fun.started -= instance.OnAlien3Fun;
            @Alien3Fun.performed -= instance.OnAlien3Fun;
            @Alien3Fun.canceled -= instance.OnAlien3Fun;
            @Alien3Hunger.started -= instance.OnAlien3Hunger;
            @Alien3Hunger.performed -= instance.OnAlien3Hunger;
            @Alien3Hunger.canceled -= instance.OnAlien3Hunger;
            @Alien4Health.started -= instance.OnAlien4Health;
            @Alien4Health.performed -= instance.OnAlien4Health;
            @Alien4Health.canceled -= instance.OnAlien4Health;
            @Alien4Taser.started -= instance.OnAlien4Taser;
            @Alien4Taser.performed -= instance.OnAlien4Taser;
            @Alien4Taser.canceled -= instance.OnAlien4Taser;
            @Alien4Hunger.started -= instance.OnAlien4Hunger;
            @Alien4Hunger.performed -= instance.OnAlien4Hunger;
            @Alien4Hunger.canceled -= instance.OnAlien4Hunger;
        }

        public void RemoveCallbacks(IInputsActions instance)
        {
            if (m_Wrapper.m_InputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_InputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InputsActions @Inputs => new InputsActions(this);
    public interface IInputsActions
    {
        void OnAlien1Hunger(InputAction.CallbackContext context);
        void OnAlien1Fun(InputAction.CallbackContext context);
        void OnAlien1Taser(InputAction.CallbackContext context);
        void OnAlien2Fun(InputAction.CallbackContext context);
        void OnAlien2Taser(InputAction.CallbackContext context);
        void OnAlien2Health(InputAction.CallbackContext context);
        void OnAlien3Health(InputAction.CallbackContext context);
        void OnAlien3Fun(InputAction.CallbackContext context);
        void OnAlien3Hunger(InputAction.CallbackContext context);
        void OnAlien4Health(InputAction.CallbackContext context);
        void OnAlien4Taser(InputAction.CallbackContext context);
        void OnAlien4Hunger(InputAction.CallbackContext context);
    }
}
